name: Docker Image CI

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

env:
  IMAGE_NAME: aassuhendar/alpine-based

jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - id: docker_meta
        name: Docker Metadaa
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME}}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-Alpine
          push: true
          # tags: ${{ secrets.DOCKERHUB_USERNAME }}/alpine-based:3.18.2
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}